credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: '$2b$12$1xkXMqxak8h8cfTqWike3O7daviSDVUaI0iLzHLEl9GPFZ5lyNcY.' # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: '$2b$12$OdWWY/mwW3tdmJ87i7JS0OgIbBhaBujxhG4ucIZ7ZF5/fnK/zT/36' # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com